In [ ]:
import pandas as pd

In [ ]:
url = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv'

dados = pd.read_csv(url)
dados

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
1         Ana     18    NaN     False
2       Cátia     27    2.5     False
3       Denis     18    5.0     False
4        Beto     21   10.0      True
5       Bruna     23    NaN     False
6        Dara     21    7.0      True
7      Carlos     19    6.0      True
8       Alice     35    5.6     False
9       Vitor     28    NaN     False
10     Daniel     21    NaN     False
11       Igor     24    4.5     False
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
14      Paulo     37    NaN     False
15     Mylena     29    7.0      True
16      Lucas     33    NaN     False
17      Nadia     34    8.0      True

In [ ]:
dados.isnull().value_counts()

Nome   Idade  Notas  Aprovado
False  False  False  False       12
              True   False        6
Name: count, dtype: int64

In [ ]:
dados = dados.fillna(0)

In [ ]:
dados

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
1         Ana     18    0.0     False
2       Cátia     27    2.5     False
3       Denis     18    5.0     False
4        Beto     21   10.0      True
5       Bruna     23    0.0     False
6        Dara     21    7.0      True
7      Carlos     19    6.0      True
8       Alice     35    5.6     False
9       Vitor     28    0.0     False
10     Daniel     21    0.0     False
11       Igor     24    4.5     False
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
14      Paulo     37    0.0     False
15     Mylena     29    7.0      True
16      Lucas     33    0.0     False
17      Nadia     34    8.0      True

In [ ]:
# Removendo essa coluna

dados.drop(7, axis=0, inplace=True)

In [ ]:
dados

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
1         Ana     18    0.0     False
2       Cátia     27    2.5     False
3       Denis     18    5.0     False
4        Beto     21   10.0      True
5       Bruna     23    0.0     False
6        Dara     21    7.0      True
8       Alice     35    5.6     False
9       Vitor     28    0.0     False
10     Daniel     21    0.0     False
11       Igor     24    4.5     False
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
14      Paulo     37    0.0     False
15     Mylena     29    7.0      True
16      Lucas     33    0.0     False
17      Nadia     34    8.0      True

In [ ]:
# Filtro buscando alunos aprovados
# precisamos trocar o true or false para 0 = reprovado e 1 aprovado

dados['Aprovado'].value_counts()

Aprovado
False    10
True      7
Name: count, dtype: int64

In [ ]:

dados['Aprovado'] = dados['Aprovado'].astype(int)

In [ ]:
aprovados = dados['Aprovado'] == 1
dados[aprovados]

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5         1
4        Beto     21   10.0         1
6        Dara     21    7.0         1
12  Sthefanie     26    9.5         1
13      Mirla     25    9.0         1
15     Mylena     29    7.0         1
17      Nadia     34    8.0         1

In [ ]:
# Salvando os aprovados em um arquivo
alunos_aprovados = dados[aprovados]

alunos_aprovados.to_csv('alunos_aprovados.csv', index=False)

In [ ]:
alunos_aprovados

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5         1
4        Beto     21   10.0         1
6        Dara     21    7.0         1
12  Sthefanie     26    9.5         1
13      Mirla     25    9.0         1
15     Mylena     29    7.0         1
17      Nadia     34    8.0         1

In [ ]:
# Atividades extras
# 1) Os alunos participaram de uma atividade extracurricular e ganharam pontos extras.
# Esses pontos extras correspondem a 40% da nota atual de cada um deles. Com base nisso,
# crie uma coluna chamada "Pontos_extras" que contenha os pontos extras de cada aluno, ou seja, 40% da nota atual deles.

dados['Nota_extra'] = dados['Notas'] * 0.40
dados

         Nome  Idade  Notas  Aprovado  Nota_extra
0         Ary     20    7.5      True        3.00
1         Ana     18    NaN     False         NaN
2       Cátia     27    2.5     False        1.00
3       Denis     18    5.0     False        2.00
4        Beto     21   10.0      True        4.00
5       Bruna     23    NaN     False         NaN
6        Dara     21    7.0      True        2.80
7      Carlos     19    6.0      True        2.40
8       Alice     35    5.6     False        2.24
9       Vitor     28    NaN     False         NaN
10     Daniel     21    NaN     False         NaN
11       Igor     24    4.5     False        1.80
12  Sthefanie     26    9.5      True        3.80
13      Mirla     25    9.0      True        3.60
14      Paulo     37    NaN     False         NaN
15     Mylena     29    7.0      True        2.80
16      Lucas     33    NaN     False         NaN
17      Nadia     34    8.0      True        3.20

In [ ]:
# 2) Crie mais uma coluna, chamada "Notas_finais" que possua as notas de cada aluno somada com os pontos extras.

dados['Notas_Finais'] = dados['Notas'] + dados['Nota_extra']
dados

         Nome  Idade  Notas  Aprovado  Nota_extra  Notas_Finais
0         Ary     20    7.5      True        3.00         10.50
1         Ana     18    NaN     False         NaN           NaN
2       Cátia     27    2.5     False        1.00          3.50
3       Denis     18    5.0     False        2.00          7.00
4        Beto     21   10.0      True        4.00         14.00
5       Bruna     23    NaN     False         NaN           NaN
6        Dara     21    7.0      True        2.80          9.80
7      Carlos     19    6.0      True        2.40          8.40
8       Alice     35    5.6     False        2.24          7.84
9       Vitor     28    NaN     False         NaN           NaN
10     Daniel     21    NaN     False         NaN           NaN
11       Igor     24    4.5     False        1.80          6.30
12  Sthefanie     26    9.5      True        3.80         13.30
13      Mirla     25    9.0      True        3.60         12.60
14      Paulo     37    NaN     False         NaN           NaN
15     Mylena     29    7.0      True        2.80          9.80
16      Lucas     33    NaN     False         NaN           NaN
17      Nadia     34    8.0      True        3.20         11.20

3) Como houve uma pontuação extra, alguns alunos que não tinham sido aprovados antes podem ter sido aprovados agora. Com base nisso, crie uma coluna chamada "Aprovado_final" com os seguintes valores:

True: caso o aluno esteja aprovado (nota final deve ser maior ou igual a 6);

False: caso o aluno esteja reprovado (nota final deve ser menor que 6).

In [ ]:
dados['Aprovado_final'] = dados['Notas_Finais'].apply(lambda x:'True' if x > 6 else 'False')
dados

         Nome  Idade  Notas Aprovado  Nota_extra  Notas_Finais Aprovado_final
0         Ary     20    7.5        1        3.00         10.50           True
1         Ana     18    NaN        0         NaN           NaN          False
2       Cátia     27    2.5        0        1.00          3.50          False
3       Denis     18    5.0        0        2.00          7.00           True
4        Beto     21   10.0        1        4.00         14.00           True
5       Bruna     23    NaN        0         NaN           NaN          False
6        Dara     21    7.0        1        2.80          9.80           True
7      Carlos     19    6.0        1        2.40          8.40           True
8       Alice     35    5.6        0        2.24          7.84           True
9       Vitor     28    NaN        0         NaN           NaN          False
10     Daniel     21    NaN        0         NaN           NaN          False
11       Igor     24    4.5        0        1.80          6.30           True
12  Sthefanie     26    9.5        1        3.80         13.30           True
13      Mirla     25    9.0        1        3.60         12.60           True
14      Paulo     37    NaN        0         NaN           NaN          False
15     Mylena     29    7.0        1        2.80          9.80           True
16      Lucas     33    NaN        0         NaN           NaN          False
17      Nadia     34    8.0        1        3.20         11.20           True

4) Faça uma seleção e verifique quais alunos não tinham sido aprovados anteriormente, mas foram aprovados após a soma dos pontos extras.

In [ ]:
#Validando as mudanças que ocorreram

dados['Aprovado_final'].value_counts()

Aprovado_final
True     11
False     7
Name: count, dtype: int64

In [ ]:
#Validando as mudanças que ocorreram

dados['Aprovado'].value_counts()

Aprovado
0    10
1     8
Name: count, dtype: int64

In [ ]:
# Para ter certeza vou converter as duas colunas para um tipo só

dados['Aprovado'] = dados['Aprovado'].astype(str)

In [ ]:
filtro_1 = dados['Aprovado'] == '0'
filtro_2 = dados['Aprovado_final'] == 'True'

filtro_completo = filtro_1 & filtro_2


resultado = dados[filtro_completo][['Nome', 'Aprovado', 'Aprovado_final']]

resultado

     Nome Aprovado Aprovado_final
3   Denis        0           True
8   Alice        0           True
11   Igor        0           True