<a href="https://colab.research.google.com/github/LaviniBastos/FormacaoFlyEducacao-Alura/blob/main/Projeto_conexao_banco_de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Desafio: manipulando um banco de dados

Você é responsável por criar um banco de dados local de clientes para uma instituição financeira.

Sua missão é:

- Criar o banco de dados local com a biblioteca SQLAlchemy.
- Escrever os dados do arquivo CSV neste banco de dados local.
- Realizar três atualizações no banco de dados:
1. Atualizar o registro do cliente de ID 6840104 que teve o rendimento anual alterado para 300000.
2. Excluir o registro do cliente de ID 5008809, pois essa pessoa não possui mais conta na instituição financeira.
3. Criar um novo registro de cliente seguindo as especificações abaixo:

- ID_Cliente: 6850985
- Idade: 33
-Grau_escolaridade: Doutorado
- Estado_civil: Solteiro
- Tamanho_familia: 1
- Categoria_de_renda: Empregado
- Ocupacao: TI
- Anos_empregado: 2
- Rendimento_anual: 290000
- Tem_carro: 0
- Moradia: Casa/apartamento próprio

In [1]:
# Importando as bibliotecas

import pandas as pd
import sqlalchemy
from sqlalchemy import create_engine, MetaData, Table, inspect, text # Criar a conexão com o Banco de dados / Representação dos metadados do banco de dados / Representação de tabelas / Inspeciona a estrtura geral do banco de dados( colunas, tabelas e etc)

In [4]:
## Criando a conexão com o banco local Sqlite que trabalha junto com o colab

engine = create_engine('sqlite:///:memory:')

In [5]:
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv'

clientes_dados = pd.read_csv(url)
clientes_dados

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,135000.0,0,Casa/apartamento próprio
438459,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438460,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438461,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438462,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [6]:
## Criar o banco de dados local com a biblioteca SQLAlchemy.

clientes_dados.to_sql('clientes', engine, index=False)

438463

In [8]:
## Testando se ocorreu tudo bem utilizando a função inspect

inspector = inspect(engine)
print(inspector.get_table_names()) # Usando a função que retorna o nome das tabelas que tem dentro do banco de dados

['clientes']

In [9]:
## Atividades

# 1 - Atualizar o registro do cliente de ID 6840104 que teve o rendimento anual alterado para 300000.

query = 'UPDATE clientes SET 	Rendimento_anual = "300000" WHERE ID_Cliente=6840104'
with engine.connect() as conn:
  result = conn.execute(text(query))
  conn.commit()

In [10]:
# Verificando a mudança

pd.read_sql_table('clientes', engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,300000.0,0,Casa/apartamento próprio
438459,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438460,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438461,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438462,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [12]:
## Atividade 2: Excluir o registro do cliente de ID 5008809, pois essa pessoa não possui mais conta na instituição financeira.

query = 'DELETE FROM clientes WHERE ID_Cliente=5008809'
with engine.connect() as conn:
  result = conn.execute(text(query))
  conn.commit()

In [13]:
# Verificando a mudança

pd.read_sql_table('clientes', engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008810,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438457,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,300000.0,0,Casa/apartamento próprio
438458,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438459,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438460,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438461,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

Atividade 3:

Criar um novo registro de cliente seguindo as especificações abaixo:

ID_Cliente: 6850985

Idade: 33 -Grau_escolaridade: Doutorado

Estado_civil: Solteiro

Tamanho_familia: 1

Categoria_de_renda: Empregado

Ocupacao: TI

Anos_empregado: 2

Rendimento_anual: 290000

Tem_carro: 0

Moradia: Casa/apartamento próprio

In [14]:
query = "INSERT INTO clientes ( ID_Cliente, Idade, Grau_escolaridade, Estado_civil, Tamanho_familia, Categoria_de_renda, Ocupacao, Anos_empregado, Rendimento_anual, Tem_carro, Moradia ) VALUES (6850985, 33, 'Doutorado', 'Solteiro', 1, 'Empregado', 'TI', 2, 290000, 0, 'Casa/apartamento próprio' )"
with engine.connect() as conn:
  result = conn.execute(text(query))
  conn.commit()

In [15]:
# Verificando a mudança

pd.read_sql_table('clientes', engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008810,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438459,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438460,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438461,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio
438462,6850985,33,Doutorado,Solteiro,1,Empregado,TI,2,290000.0,0,Casa/apartamento próprio

Conseguimos ver que o registro adicionado é exatamente a última linha do DataSet. **Desafio concluido com sucesso!!**